version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ~/docker/postgres-db:/data/postgres
    ports:
      - "5432:5432"
  talkable:
    build: .
    env_file: .env
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/talkable
    ports:
      - "9292:3000"
    depends_on:
      - postgres
volumes:
  postgres-db:
    driver: local
